# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation_date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated_date')),
                ('name', models.CharField(max_length=191, verbose_name='Product')),
                ('about', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Price')),
                ('image', models.ImageField(blank=True, default='', upload_to=shop.models.make_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation_date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated_date')),
                ('number', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
